version: '3.3'
services:
  openldap:
    image: osixia/openldap:1.4.0
    container_name: vault-openldap
    environment:
      - LDAP_ORGANISATION=vault-clj
      - LDAP_DOMAIN=test.com
      - LDAP_ADMIN_PASSWORD=ldap-admin
    ports:
      - '389:389'

  postgres:
    image: postgres:11-alpine
    container_name: vault-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hunter2
    ports:
      - "5432:5432"
